// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test() {
    driver.get("https://bstackdemo.com/");
    driver.manage().window().setSize(new Dimension(945, 1012));
    driver.findElement(By.cssSelector("#\\32 > .shelf-item__buy-btn")).click();
    driver.findElement(By.cssSelector(".App")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".App"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".change-product-button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".change-product-button:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".change-product-button:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".change-product-button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".change-product-button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".change-product-button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".m-auto")).click();
    driver.findElement(By.cssSelector(".float-cart__close-btn")).click();
    driver.findElement(By.cssSelector(".filters-available-size:nth-child(3) .checkmark")).click();
    driver.findElement(By.id("10")).click();
    driver.findElement(By.id("10")).click();
    {
      WebElement element = driver.findElement(By.id("10"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("10")).click();
    driver.findElement(By.cssSelector("#\\31 0 > .shelf-item__buy-btn")).click();
    driver.findElement(By.cssSelector("#\\31 0 > .shelf-item__buy-btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#\\31 0 > .shelf-item__buy-btn"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("#\\31 0 > .shelf-item__buy-btn")).click();
    driver.findElement(By.cssSelector("#\\31 0 > .shelf-item__buy-btn")).click();
    driver.findElement(By.cssSelector("#\\31 0 > .shelf-item__buy-btn")).click();
    driver.findElement(By.cssSelector(".shelf-item:nth-child(2) .change-product-button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".buy-btn")).click();
    driver.findElement(By.cssSelector(".css-1pahdxg-control .css-1wa3eu0-placeholder")).click();
    driver.findElement(By.id("react-select-2-input")).sendKeys("demouser");
    driver.findElement(By.id("react-select-2-input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".css-1wa3eu0-placeholder")).click();
    driver.findElement(By.id("react-select-3-input")).sendKeys("testingisfun99");
    driver.findElement(By.id("react-select-3-input")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("login-btn")).click();
    driver.findElement(By.id("firstNameInput")).click();
    driver.findElement(By.id("lastNameInput")).click();
    driver.findElement(By.id("lastNameInput")).sendKeys("asd");
    driver.findElement(By.id("addressLine1Input")).click();
    driver.findElement(By.id("addressLine1Input")).sendKeys("dsa");
    driver.findElement(By.id("provinceInput")).click();
    driver.findElement(By.id("provinceInput")).sendKeys("dsa");
    driver.findElement(By.id("postCodeInput")).click();
    driver.findElement(By.id("postCodeInput")).sendKeys("dsa");
    driver.findElement(By.id("checkout-shipping-continue")).click();
    {
      WebElement element = driver.findElement(By.id("checkout-shipping-continue"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".button")).click();
    driver.close();
  }
}
